Changes to make it work with my repos and workflow

diff --git a/ecs-deploy b/ecs-deploy
--- a/ecs-deploy
+++ b/ecs-deploy
@@ -124,104 +124,58 @@ if [ $IMAGE == false ]; then
     exit 1
 fi
 
-# Define regex for image name
-# This regex will create groups for:
-# - domain
-# - port
-# - repo
-# - image
-# - tag
-# If a group is missing it will be an empty string
-imageRegex="^([a-zA-Z0-9.\-]+):?([0-9]+)?/([a-zA-Z0-9\-]+)/?([a-zA-Z0-9\-]+)?:?([a-zA-Z0-9\-\.]+)?$"
-
-if [[ $IMAGE =~ $imageRegex ]]; then
-  # Define variables from matching groups
-  domain=${BASH_REMATCH[1]}
-  port=${BASH_REMATCH[2]}
-  repo=${BASH_REMATCH[3]}
-  img=${BASH_REMATCH[4]}
-  tag=${BASH_REMATCH[5]}
-
-  # Validate what we received to make sure we have the pieces needed
-  if [[ "x$domain" == "x" ]]; then
-    echo "Image name does not contain a domain or repo as expected. See usage for supported formats." && exit 1;
-  fi
-  if [[ "x$repo" == "x" ]]; then
-    echo "Image name is missing the actual image name. See usage for supported formats." && exit 1;
-  fi
-
-  # When a match for image is not found, the image name was picked up by the repo group, so reset variables
-  if [[ "x$img" == "x" ]]; then
-    img=$repo
-    repo=""
-  fi
-
-else
-  # check if using root level repo with format like mariadb or mariadb:latest
-  rootRepoRegex="^([a-zA-Z0-9\-]+):?([a-zA-Z0-9\.\-]+)?$"
-  if [[ $IMAGE =~ $rootRepoRegex ]]; then
-    img=${BASH_REMATCH[1]}
-    if [[ "x$img" == "x" ]]; then
-      echo "Invalid image name. See usage for supported formats." && exit 1
-    fi
-    tag=${BASH_REMATCH[2]}
-  else
-    echo "Unable to parse image name: $IMAGE, check the format and try again" && exit 1
-  fi
-fi
-
-# If tag is missing make sure we can get it from env var, or use latest as default
-if [[ "x$tag" == "x" ]]; then
-  if [[ $TAGVAR == false ]]; then
-    tag="latest"
-  else
-    tag=${!TAGVAR}
-    if [[ "x$tag" == "x" ]]; then
-      tag="latest"
-    fi
-  fi
-fi
-
-# Reassemble image name
-useImage=""
-if [[ "x$domain" != "x" ]]; then
-  useImage="$domain"
-fi
-if [[ "x$port" != "x" ]]; then
-  useImage="$useImage:$port"
-fi
-if [[ "x$repo" != "x" ]]; then
-  useImage="$useImage/$repo"
-fi
-if [[ "x$img" != "x" ]]; then
-  if [[ "x$useImage" == "x" ]]; then
-    useImage="$img"
-  else
-    useImage="$useImage/$img"
-  fi
-fi
-if [[ "x$tag" != "x" ]]; then
-  useImage="$useImage:$tag"
-fi
+useImage=$IMAGE
 
 echo "Using image name: $useImage"
 
 # Get current task definition name from service
 TASK_DEFINITION=`aws ecs describe-services --services $SERVICE --cluster $CLUSTER | jq .services[0].taskDefinition | tr -d '"'`
 echo "Current task definition: $TASK_DEFINITION";
+DESIRED_COUNT=`aws ecs describe-services --services $SERVICE --cluster $CLUSTER | jq .services[0].desiredCount`
+CONTAINER_COUNT=`aws ecs list-container-instances --cluster $CLUSTER | jq '.containerInstanceArns[]' | wc -l | xargs`
 
 # Get a JSON representation of the current task definition
 aws ecs describe-task-definition --task-def $TASK_DEFINITION > def
 
 # Update definition to use new image name
-sed -i def -e "s|\"image\": \".*\"|\"image\": \"${useImage}\"|"
+#sed -i def -e "s|\"image\": \".*\"|\"image\": \"${useImage}\"|"
+cat def | sed -e "s|\"image\": \".*\"|\"image\": \"${useImage}\"|" > updated
 
 # Filter the def
-jq < def > newdef '.taskDefinition|{family: .family, volumes: .volumes, containerDefinitions: .containerDefinitions}'
+#jq < def > newdef '.taskDefinition|{family: .family, volumes: .volumes, containerDefinitions: .containerDefinitions}'
+jq < updated > newdef '.taskDefinition|{family: .family, volumes: .volumes, containerDefinitions: .containerDefinitions}'
 
 # Register the new task definition, and store its ARN
 NEW_TASKDEF=`aws ecs register-task-definition --cli-input-json file://newdef | jq .taskDefinition.taskDefinitionArn | tr -d '"'`
 echo "New task definition: $NEW_TASKDEF";
+
+# Before we Update the service, check a few things
+if [ $DESIRED_COUNT -gt 1 ] && [ $CONTAINER_COUNT -gt 1 ] && [ $DESIRED_COUNT -ge $CONTAINER_COUNT ]; then
+  DESIRED_COUNT_ORIG=$DESIRED_COUNT
+  DESIRED_COUNT=$(( CONTAINER_COUNT-1 ))
+  aws ecs update-service --cluster $CLUSTER --service $SERVICE --desired-count $DESIRED_COUNT
+  echo "Service desiredCount changed successfully, new desiredCount set.";
+
+  every=10
+  i=0
+  while [ $i -lt $TIMEOUT ]
+  do
+    # Grab the running task count to see if our update has taken place
+    RUNNING_COUNT=`aws ecs describe-services --services $SERVICE --cluster $CLUSTER | jq .services[0].runningCount`
+    if [ $RUNNING_COUNT -eq $DESIRED_COUNT  ]; then
+      echo "Tasks updated successfully, set number of tasks running.";
+      break
+    fi
+    sleep $every
+    i=$(( $i + $every ))
+  done
+fi
+
+if [ $CONTAINER_COUNT -eq 1  ] && [ $DESIRED_COUNT -eq 1 ]; then
+  # We only have one container, so we'll need to kill off the service first
+  TASK_ID=`aws ecs list-tasks --cluster respondr-messaging  --service-name dev --profile respondr  | jq '.taskArns[]' | tr "\"" " " | awk -F'/' '{print $2}'`
+  aws ecs stop-task --task TASK_ID --cluster $CLUSTER;
+fi
 
 # Update the service
 UPDATE=`aws ecs update-service --cluster $CLUSTER --service $SERVICE --task-definition $NEW_TASKDEF`
@@ -245,13 +199,36 @@ do
 
   if [ "$RUNNING" ]; then
     echo "Service updated successfully, new task definition running.";
-    exit 0
+    #exit 0
+    break
   fi
 
   sleep $every
   i=$(( $i + $every ))
 done
 
+# Let the services settle, then set things back
+if [ $CONTAINER_COUNT -ge $DESIRED_COUNT  ] && [ $DESIRED_COUNT -lt $DESIRED_COUNT_ORIG ]; then
+  every=10
+  i=0
+  while [ $i -lt $TIMEOUT ]
+  do
+    RUNNING_COUNT=`aws ecs describe-services --services $SERVICE --cluster $CLUSTER | jq .services[0].runningCount`
+    if [ $RUNNING_COUNT -eq $DESIRED_COUNT ]; then
+
+    DESIRED_COUNT=$DESIRED_COUNT_ORIG
+    aws ecs update-service --cluster $CLUSTER --service $SERVICE --desired-count $DESIRED_COUNT
+    echo "Service desiredCount set back to original count successfully, new desiredCount set.";
+    fi
+
+    sleep $every
+    i=$(( $i + $every ))
+  done
+fi
+
+# Remove temporary files from the deployment
+rm -rf d1 def newdef results tasks updated
+
 # Timeout
-echo "ERROR: New task definition not running within $TIMEOUT seconds"
-exit 1
+#echo "ERROR: New task definition not running within $TIMEOUT seconds"
+#exit 1
